export { default as ExplorerWindow } from "./ExplorerWindow";
export { default as IframeWindow } from "./IframeWindow";
export { default as InternetExplorer } from "./InternetExplorer";
export { default as JSDos } from "./JSDos";
export { default as Notepad } from "./Notepad";
export { default as Doom } from "./Doom"
export { default as Burn } from "./Burn"
export { default as Pipes } from "./Pipes"
export { default as Sand } from "./Sand"
export { default as Minesweeper2 } from "./Minesweeper2";
export { default as VideoPlayer } from "./VideoPlayer";
